# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])
print(arr)

[23 42 13  7  0]


In [4]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x13173bb23f0
byteorder:  little
byteswap:  False
type: int32


In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.40675594 0.92959432 0.37179249]
 [0.14191139 0.18992995 0.6579878 ]
 [0.79060004 0.94682266 0.79666316]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [10]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.40675594 0.92959432 0.37179249]
 [0.14191139 0.18992995 0.6579878 ]
 [0.79060004 0.94682266 0.79666316]]
...
float64
(3, 3)
3
2
9
8
72


In [11]:
arr.__sizeof__()

192

### ЗАВДАННЯ 1

In [12]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype='f2')
print(arr1_1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [13]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array([1,2,3,4], dtype='S')
print(arr1_2)

[b'1' b'2' b'3' b'4']


In [14]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3,4))
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [15]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array([spisok[:5],spisok[5:]], dtype='f2')
print(arr)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [16]:
#преретворити форму масива `reshape` 
arr = arr.reshape((5,2))
print(arr)
print(arr.dtype)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
float16


In [17]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('i4')
print(arr)
print(arr.dtype)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
int32


In [18]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### ЗАВДАННЯ 2

In [19]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.full((3,1,3), False)
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [20]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape((3,3))
arr2_2 = arr2_2.astype('i4')
print(arr2_2,'\n')

[[0 0 0]
 [0 0 0]
 [0 0 0]] 



In [21]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10, 21, 2)
arr2_3 = arr.reshape((2,5))
print(arr2_3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [22]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [23]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[19 18 28 13]
 [26 36 19 39]
 [21 41 43 11]
 [26 32 36 15]]


In [24]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, 3]
print(el)

39


In [25]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[26 32 36 15]


In [26]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[19 18 28 13]
 [26 36 19 39]]


In [27]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[18 28]
 [36 19]
 [41 43]
 [32 36]]


In [28]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[19 18 28 13]
 [21 41 43 11]]


In [29]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[28 26 36 39 21 41 43 26 32 36]


### ЗАВДАННЯ 3

In [30]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.random.randint(10, 100, (4,5))
print(arr3_1)

[[69 86 87 25 28]
 [87 57 35 27 47]
 [23 95 11 21 70]
 [71 83 98 66 89]]


In [31]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1][2]
print(el3_2)

35


In [32]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[87 57 35 27 47]


In [33]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[0:4,2:3]
print(vect3_4)

[[87]
 [35]
 [11]
 [98]]


In [34]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3,1:3]
print(mat3_5)

[[57 35]
 [95 11]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [35]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [37]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.41086249 0.50844288 0.29167412 0.93138384 0.52131037]
 [0.61516452 0.57404893 0.60951533 0.88541694 0.73883168]
 [0.03683852 0.71532269 0.95962391 0.90940614 0.43116276]
 [0.87728564 0.29287436 0.67665971 0.17471244 0.84481509]
 [0.66037467 0.48670844 0.94963589 0.72408269 0.82357008]]
...
[0.41086249 0.57404893 0.95962391 0.17471244 0.82357008]


In [38]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.41086249 0.61516452 0.03683852 0.87728564 0.66037467]
 [0.50844288 0.57404893 0.71532269 0.29287436 0.48670844]
 [0.29167412 0.60951533 0.95962391 0.67665971 0.94963589]
 [0.93138384 0.88541694 0.90940614 0.17471244 0.72408269]
 [0.52131037 0.73883168 0.43116276 0.84481509 0.82357008]]


In [39]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

0.0006772493960454388


In [40]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[ -74.30026202  106.71688253  -12.70916728  -29.43390486  -11.85860168]
 [ -17.41746622   26.73413737    0.42264231   -3.01079254  -10.09117092]
 [ -23.92919677   31.87925228   -3.61216416  -10.0642809    -1.23726683]
 [  -7.28414271   11.14209854   -2.73385208   -5.7528069     1.94756599]
 [ 103.8667948  -147.92467825   16.50968702   42.04340884   16.40095082]]


### ЗАВАДАННЯ 4

In [41]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.random.randint(100, 200, (6,6))
print(mat4_1,'\n')
print(mat4_1.dtype,'- інспектування типу массиву `dtype`')
print(mat4_1.ndim,'- інспектування кількості вимірів масиву `ndim`')

[[126 137 144 186 173 157]
 [195 114 173 135 159 144]
 [101 148 131 190 101 168]
 [126 130 130 118 106 157]
 [197 156 157 139 135 117]
 [139 197 162 128 183 186]] 

int32 - інспектування типу массиву `dtype`
2 - інспектування кількості вимірів масиву `ndim`


In [42]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[126 114 131 118 135 186]


In [43]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[126 195 101 126 197 139]
 [137 114 148 130 156 197]
 [144 173 131 130 157 162]
 [186 135 190 118 139 128]
 [173 159 101 106 135 183]
 [157 144 168 157 117 186]]


In [44]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[ 2.54074369e-02 -2.75057130e-02 -3.39406616e-02  5.20168014e-02
   1.73325238e-02 -2.43046068e-02]
 [-4.85995980e-03 -1.08586449e-02  3.08412186e-03 -5.65160830e-03
   1.01837025e-02  8.08782466e-03]
 [-6.48682330e-02  6.98375850e-02  6.91957264e-02 -1.02680449e-01
  -2.69363755e-02  4.18021761e-02]
 [ 9.65292541e-03 -5.69645168e-03  2.64339783e-03 -5.58003822e-05
   4.37605954e-03 -8.83091070e-03]
 [ 1.91906873e-02 -7.67696959e-03 -1.74638817e-02  7.17734287e-03
   1.23153592e-04 -6.17064330e-04]
 [ 1.71342035e-02 -1.72968300e-02 -2.28064102e-02  4.95212522e-02
  -3.41069948e-03 -1.47507220e-02]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [45]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [46]:
# вирахувати суму елеметнів
s = np.sum(vect)
print(s)
# знайти мінімальний ел-т
m = np.min(vect)
print(vect)
# відсортувати вектор по зростанню
vs = np.sort(vect)
print(vs)
# знайти середнє значення
mid = np.average(vect)
print(mid)

8
[ 1  3  2 -3  5  0]
[-3  0  1  2  3  5]
1.3333333333333333


In [47]:
# матриця 3х4 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [48]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [49]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [50]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [51]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [52]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [53]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


C:\Users\stani\AppData\Local\Temp\ipykernel_8856\3347190385.py:2: RuntimeWarning: divide by zero encountered in true_divide
  K = N / M


In [54]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [55]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [56]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [57]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [58]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [59]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[3 1 6 4 9]
[3 1 6 4 9]
1311938541968 1311938541968
[3 1 6 4 9]
1311938541968 1311938502992


In [60]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [61]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.randint(0, 10, (3,4))
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1, axis=0)
print(sum_mat5_1)

[[1 7 4 8]
 [8 4 8 0]
 [9 2 8 3]]
[18 13 20 11]


In [62]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(mat5_1)
print(min_mat5_1)

0


In [63]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1+100
print(mat5_3)

[[101 107 104 108]
 [108 104 108 100]
 [109 102 108 103]]


In [64]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_4 = np.diag(np.diag(mat5_3))
print(mat5_1)
print(mat5_4)
mat5_1 = np.dot(mat5_4, mat5_1)
print(mat5_4)

[[1 7 4 8]
 [8 4 8 0]
 [9 2 8 3]]
[[101   0   0]
 [  0 104   0]
 [  0   0 108]]
[[101   0   0]
 [  0 104   0]
 [  0   0 108]]


In [65]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.concatenate((mat5_3, mat5_4), axis=1)
print(mat5_5)
print('rank -',np.linalg.matrix_rank(mat5_5))

[[101 107 104 108 101   0   0]
 [108 104 108 100   0 104   0]
 [109 102 108 103   0   0 108]]
rank - 3
